<?php

namespace App\Constants;

class EmergencyComplaints
{
    public const ALL = [
        'Medical Emergency',
        'Cardiac Emergency',
        'Respiratory Emergency',
        'Diabetic Emergency',
        'Psychiatric Emergency',
        'Motor Vehicular Accidents',
        'Motor Vehicular Accidents (Pedestrian)',
        'Mass Casualty Incident (Trauma)',
        'Mass Casualty Incident (Medical, Infectious)',
        'Industrial Accident',
        'Transport Home to Hospital',
        'Transport for Check Up',
        'Transport for Referral',
        'Transport for Hospital Admission',
        'Transport (Cadaver)',
        'Public Service',
        'Training',
        'Stand-By Unit',
        'COVID-19 Transport',
        'Calls (Emergency, Assistance and Inquiry)',
        'Hazardous Condition',
        'Hazardous Materials',
        'Severe Weather',
        'Search and Rescue/ Retrieval',
        'Water Rescue/Drowning Incident',
        'Evacuation Center Management',
        'Bomb Threat',
        'Hostage Situation',
        'Fire Incidents',
        'Terrorism',
        'Assault',
        'Missing Persons',
        'Bleeding',
        'Hemorrhage/Laceration/Abrasion',
        'Trauma',
        'Fall Victim',
        'Fracture/Dislocation',
        'Abdominal Pain',
        'Back Pain',
        'Headache',
        'Eye Problem',
        'Breathing Problems/Difficulty of Breathing',
        'Burns',
        'Electrical Shock',
        'Allergic Reaction',
        'Overdose',
        'Flu-like Symptoms',
        'Unconscious',
        'Seizures',
        'Pregnancy/Childbirth',
        'Wound Dressing/First Aid',
        'Dead',
        'Nausea and Vomiting',
        'COVID Transport',
        'Waiver',
        'Fainting',
        'Suicide',
        'CVA (Stroke)',
        'Animal Bite',
        'Stab Wound',
        'Hypertensive Emergency',
        'Psychosomatic Disorder',
        'Post Operative Case',
        'Loss of Bowel Movement/Mild Dehydration',
        'Chest Pain',
        'Body Weakness',
        'Attempted Suicide',
    ];
}
